# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa44d574d950c497b1ed812c21582913199cc6f0fd59b2d9759d2c8ebe941e71b975ad111f70eaaac483c92cfbd1f043ddef0ccb4db52a3bed54845d2b2a75f4

test:
  secret_key_base: 61cd7fe3209b5cbdb0f068b7166d47633d539a5c7446da36777855acb276d2dbbc8f26aabb1aaacf21b33f927fd2372f97870dc5e883404d9603fb7315242610

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
